
/** Event categories with their pill/dot variant keys */
export const EVENT_CATEGORIES = [
  { id: 'official', label: 'Official Events', dotClass: 'dot-official' },
  { id: 'club', label: 'Club Events', dotClass: 'dot-club' },
  { id: 'workshop', label: 'Workshops', dotClass: 'dot-workshop' },
  { id: 'guest', label: 'Guest Lectures', dotClass: 'dot-guest' },
  { id: 'cultural', label: 'Cultural & Informal', dotClass: 'dot-cultural' },
];

/** User's personal events shown in the sidebar */
export const MY_EVENTS = [
  { id: 1, title: 'Design Thinking Bootcamp', date: 'May 10', time: '10:00 AM', status: 'enrolled' },
  { id: 2, title: 'Student Web3 Meetup', date: 'May 14', time: '4:00 PM', status: 'pending' },
  { id: 3, title: 'Hackathon Kickoff', date: 'May 18', time: '9:00 AM', status: 'approved' },
  { id: 4, title: 'Gaming Night', date: 'May 20', time: '8:00 PM', status: 'rejected' },
];

/** Venue data for the accordion filter */
export const VENUES = [
  {
    id: 'block-a', name: 'Block A', roomCount: 33, expanded: true,
    floors: [
      { label: 'Floor 3', rooms: [{ id: 'A-301', active: true }, { id: 'A-302', active: false }, { id: 'A-303', active: false }, { id: 'A-304', active: false }, { id: 'A-305', active: false }] },
      { label: 'Floor 4', rooms: [{ id: 'A-401', active: true }, { id: 'A-402', active: false }, { id: 'A-403', active: false }] },
    ],
  },
  { id: 'block-c', name: 'Block C', roomCount: 2, expanded: false, floors: [] },
  { id: 'other', name: 'Other Venues', roomCount: null, expanded: false, floors: [] },
];

/** Full event data — each event has everything needed for the detail panel */
export const CALENDAR_EVENTS = {
  4: [
    {
      id: 'e1',
      title: 'Industry Talk: AI & the Future',
      room: 'Auditorium',
      category: 'guest',
      badge: 'Guest Lecture',
      shortDesc: 'An inspiring talk by top AI researchers on the real-world impact of large language models and the future of work.',
      organizer: { initials: 'TC', name: 'Tech Circle', role: 'RU Tech Society' },
      date: 'Monday, 4 May 2026',
      time: '3:00 PM — 5:00 PM',
      duration: '2 hours',
      venue: { room: 'Auditorium', detail: 'Main Campus · Ground Floor · Rishihood University', block: 'Main Block', floor: 'Ground Floor', roomLabel: 'Auditorium' },
      description: 'Join us for a riveting talk featuring industry pioneers in Artificial Intelligence. Topics include generative AI, AGI timelines, and how students can prepare for an AI-first job market.',
      tags: ['AI', 'Technology', 'Career'],
      speakers: [{ initials: 'RK', name: 'Dr. Rahul Kapoor', role: 'AI Research Lead, Google India' }],
      enrollment: { filled: 112, total: 150, percent: 75 },
    },
  ],
  8: [
    {
      id: 'e2',
      title: 'Finance Club Meetup',
      room: 'C-103',
      category: 'club',
      badge: 'Club Event',
      shortDesc: 'Monthly meetup of the RU Finance Club — discussing markets, internship opportunities, and club projects.',
      organizer: { initials: 'FC', name: 'Finance Club', role: 'Student Club' },
      date: 'Friday, 8 May 2026',
      time: '5:00 PM — 6:30 PM',
      duration: '1.5 hours',
      venue: { room: 'C-103', detail: 'Block C · First Floor · Rishihood University', block: 'Block C', floor: '1st Floor', roomLabel: 'C-103' },
      description: 'The Finance Club hosts its monthly meetup to discuss global market trends, share internship experiences, and plan upcoming events including the annual stock market simulation.',
      tags: ['Finance', 'Networking', 'Club'],
      speakers: [{ initials: 'AM', name: 'Arjun Mehta', role: 'Club President' }],
      enrollment: { filled: 28, total: 40, percent: 70 },
    },
  ],
  10: [
    {
      id: 'e3',
      title: 'Design Thinking Bootcamp',
      room: 'A-401',
      category: 'official',
      enrolled: true,
      badge: 'Official Event',
      shortDesc: 'A 3-hour intensive workshop covering the fundamentals of user-centered design and rapid prototyping.',
      organizer: { initials: 'SA', name: 'Student Affairs', role: 'Rishihood University' },
      date: 'Saturday, 10 May 2026',
      time: '10:00 AM — 1:00 PM',
      duration: '3 hours',
      venue: { room: 'A-401', detail: 'Block A · Fourth Floor · Rishihood University', block: 'Block A', floor: '4th Floor', roomLabel: 'A-401' },
      description: "Join us for an immersive hands-on session where you'll learn the core principles of Design Thinking. Apply methodologies to solve real-world problems and ideate effectively in teams.",
      tags: ['Design', 'Certificate', 'Hands-on'],
      speakers: [
        { initials: 'JD', name: 'Jane Doe', role: 'Lead Designer, TechCorp' },
        { initials: 'JS', name: 'John Smith', role: 'UX Researcher' },
      ],
      enrollment: { filled: 43, total: 60, percent: 71 },
      conflict: { text: '⚠ Conflicts with User Research 101 · 11:00–12:30 PM' },
    },
    {
      id: 'e4',
      title: 'User Research 101',
      room: 'Innovation Lab',
      category: 'workshop',
      enrolled: true,
      conflict: true,
      badge: 'Workshop',
      shortDesc: 'An introductory hands-on workshop on conducting user interviews, surveys, and usability tests.',
      organizer: { initials: 'UX', name: 'UX Guild', role: 'Design Community' },
      date: 'Saturday, 10 May 2026',
      time: '11:00 AM — 12:30 PM',
      duration: '1.5 hours',
      venue: { room: 'Innovation Lab', detail: 'Block B · Second Floor · Rishihood University', block: 'Block B', floor: '2nd Floor', roomLabel: 'Innov. Lab' },
      description: 'Learn how to run user research from scratch. This workshop covers interview techniques, synthesis methods, and how to turn user insights into actionable product decisions.',
      tags: ['UX', 'Research', 'Practical'],
      speakers: [{ initials: 'PR', name: 'Priya Reddy', role: 'Product Designer, Swiggy' }],
      enrollment: { filled: 18, total: 25, percent: 72 },
      conflict: { text: '⚠ Conflicts with Design Thinking Bootcamp · 10:00–1:00 PM' },
    },
  ],
  12: [
    {
      id: 'e5',
      title: 'Robotics Weekly Meet',
      room: 'Lab 2',
      category: 'club',
      badge: 'Club Event',
      shortDesc: 'Weekly build session for the Robotics Club — working on the inter-college bot challenge.',
      organizer: { initials: 'RC', name: 'Robotics Club', role: 'Engineering Society' },
      date: 'Tuesday, 12 May 2026',
      time: '4:00 PM — 6:00 PM',
      duration: '2 hours',
      venue: { room: 'Lab 2', detail: 'Block A · Third Floor · Rishihood University', block: 'Block A', floor: '3rd Floor', roomLabel: 'Lab 2' },
      description: 'The Robotics Club meets every week to work on ongoing projects. This session focuses on motor control integration for the upcoming Inter-College Bot Wars 2026.',
      tags: ['Robotics', 'Engineering', 'Club'],
      speakers: [{ initials: 'VB', name: 'Vivek Bhatt', role: 'Club Lead' }],
      enrollment: { filled: 15, total: 20, percent: 75 },
    },
  ],
  15: [
    {
      id: 'e6',
      title: 'Open Mic Night',
      room: 'Cafeteria',
      category: 'cultural',
      badge: 'Cultural Event',
      shortDesc: 'An open stage for students to perform poetry, music, comedy, or anything creative. All are welcome!',
      organizer: { initials: 'CC', name: 'Cultural Committee', role: 'Student Body' },
      date: 'Friday, 15 May 2026',
      time: '7:00 PM — 9:30 PM',
      duration: '2.5 hours',
      venue: { room: 'Cafeteria', detail: 'Main Campus · Ground Floor · Rishihood University', block: 'Main Block', floor: 'Ground Floor', roomLabel: 'Cafeteria' },
      description: 'Every voice deserves a stage. Bring your poems, songs, stand-up sets, or spoken word pieces. Audience members are welcome too — just come and enjoy a night of campus talent.',
      tags: ['Cultural', 'Performance', 'Open Stage'],
      speakers: [],
      enrollment: { filled: 65, total: 100, percent: 65 },
    },
  ],
  18: [
    {
      id: 'e7',
      title: 'Hackathon Kickoff',
      room: 'Auditorium',
      category: 'official',
      badge: 'Official Event',
      shortDesc: 'The grand kickoff of RU Hack 2026 — 48 hours of building, learning, and competing.',
      organizer: { initials: 'SA', name: 'Student Affairs', role: 'Rishihood University' },
      date: 'Monday, 18 May 2026',
      time: '9:00 AM — 10:00 AM',
      duration: '1 hour (Opening)',
      venue: { room: 'Auditorium', detail: 'Main Campus · Ground Floor · Rishihood University', block: 'Main Block', floor: 'Ground Floor', roomLabel: 'Auditorium' },
      description: 'RU Hack 2026 is a 48-hour hackathon open to all students. Teams of up to 4 will build solutions across tracks: Education, Health, Sustainability, and Open Innovation. The kickoff includes orientation, team formation, and the problem statement reveal.',
      tags: ['Hackathon', 'Certificate', 'Team'],
      speakers: [
        { initials: 'VP', name: 'Vice Chancellor', role: 'Rishihood University' },
        { initials: 'SK', name: 'Saurabh Kumar', role: 'Hackathon Lead' },
      ],
      enrollment: { filled: 148, total: 200, percent: 74 },
    },
  ],
  22: [
    {
      id: 'e8',
      title: 'Townhall Meeting',
      room: 'Main Audi',
      category: 'official',
      badge: 'Official Event',
      shortDesc: 'Quarterly all-student townhall with the administration — raise questions, share feedback, hear updates.',
      organizer: { initials: 'VC', name: 'Vice Chancellor\'s Office', role: 'Rishihood University' },
      date: 'Friday, 22 May 2026',
      time: '11:00 AM — 12:30 PM',
      duration: '1.5 hours',
      venue: { room: 'Main Audi', detail: 'Main Campus · Ground Floor · Rishihood University', block: 'Main Block', floor: 'Ground Floor', roomLabel: 'Main Auditorium' },
      description: 'The quarterly townhall is an open forum for all students to interact with administration. Topics include academic policy updates, campus infrastructure plans, and upcoming semester schedule changes.',
      tags: ['Official', 'Campus', 'Compulsory'],
      speakers: [{ initials: 'VC', name: 'Dr. A. Sharma', role: 'Vice Chancellor' }],
      enrollment: { filled: 900, total: 1000, percent: 90 },
    },
  ],
  26: [
    {
      id: 'e9',
      title: 'Resume Building Workshop',
      room: 'C-201',
      category: 'workshop',
      badge: 'Workshop',
      shortDesc: 'Learn how to craft a standout resume with expert guidance from placement officers and alumni.',
      organizer: { initials: 'PO', name: 'Placement Office', role: 'Career Services, RU' },
      date: 'Tuesday, 26 May 2026',
      time: '2:00 PM — 4:00 PM',
      duration: '2 hours',
      venue: { room: 'C-201', detail: 'Block C · Second Floor · Rishihood University', block: 'Block C', floor: '2nd Floor', roomLabel: 'C-201' },
      description: 'This workshop covers everything from structuring your resume, writing impactful bullet points, tailoring it for different roles, and using tools like LinkedIn to complement your profile. One-on-one review slots available.',
      tags: ['Career', 'Resume', 'Placement'],
      speakers: [
        { initials: 'NT', name: 'Neeraj Tiwari', role: 'Placement Officer' },
        { initials: 'AS', name: 'Ananya Sen (Alumni)', role: 'Product Manager, Flipkart' },
      ],
      enrollment: { filled: 34, total: 50, percent: 68 },
    },
  ],
  28: [
    {
      id: 'e10',
      title: 'Movie Screening Night',
      room: 'Auditorium',
      category: 'cultural',
      badge: 'Cultural Event',
      shortDesc: 'A relaxed Friday night screening of an award-winning indie film followed by a discussion.',
      organizer: { initials: 'CF', name: 'Cinema Forum', role: 'Student Club' },
      date: 'Thursday, 28 May 2026',
      time: '6:30 PM — 9:00 PM',
      duration: '2.5 hours',
      venue: { room: 'Auditorium', detail: 'Main Campus · Ground Floor · Rishihood University', block: 'Main Block', floor: 'Ground Floor', roomLabel: 'Auditorium' },
      description: 'Screening of "The Great Indian Kitchen" followed by a moderated discussion on its themes. Popcorn and snacks provided. Come unwind before the weekend!',
      tags: ['Film', 'Culture', 'Discussion'],
      speakers: [{ initials: 'PN', name: 'Prof. Nalini', role: 'Faculty, Film Studies' }],
      enrollment: { filled: 80, total: 120, percent: 67 },
    },
  ],
};

/** Days each month starts on (0=Sun) for 2026 */
export const MONTH_START_DAY = [4, 0, 0, 3, 5, 1, 3, 6, 2, 4, 0, 2];
export const MONTH_DAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
